export const video_games = [
  {
    title: "The Cake Shop 2",
    developer: "CD Projekt",
    release_date: "19/05/2015",
    description: "An open-world action RPG with a captivating storyline.",
    price: 129.99,
    genre: "Action",
    rating: 5,
    platform: ["PC", "PS4", "Xbox One", "Nintendo Switch"],
    img: "https://toomkygames.com/wp-content/uploads/default/games/small/Cake-Shop-320x240.jpg",
  },
  {
    title: "Tekken 3",
    developer: "Rockstar Games",
    release_date: "26/10/2018",
    description: "A western-themed action-adventure game set in an open world.",
    price: 229.99,
    genre: "Action",
    rating: 4.5,
    platform: ["PS4", "Xbox One", "PC"],
    img: "https://c4.wallpaperflare.com/wallpaper/296/962/469/anna-nina-wallpaper-thumb.jpg",
  },

  {
    title: "Need for speed 2",
    developer: "Nintendo",
    release_date: "03/03/2017",
    description:
      "An action-adventure game set in an open world, exploring Hyrule.",
    price: 59.99,
    genre: "Adventure",
    rating: 5,
    platform: ["Nintendo Switch"],
    img: "https://play-lh.googleusercontent.com/aKXKOVc6-ejZoXMcraRjPBxkreHKI_f95Y6j-JARGhj-j2qs6ma6l_g2WWKjsrCQDmc=w526-h296-rw",
  },
  {
    title: "GTA 4",
    developer: "Naughty Dog",
    release_date: "10/05/2016",
    description:
      "A thrilling action-adventure game featuring Nathan Drake's final adventure.",
    price: 679.99,
    genre: "Adventure",
    rating: 4.7,
    platform: ["PS4"],
    img: "https://5.imimg.com/data5/SELLER/Default/2020/8/XJ/AV/OJ/57036556/gta-4-pc-game-500x500.jpg",
  },
  {
    title: "Call Of Duty",
    developer: "Naughty Dog",
    release_date: "12/09/2001",
    description:
      "A thrilling action-adventure game featuring Nathan Drake's final adventure.",
    price: 876.99,
    genre: "Adventure",
    rating: 4.7,
    platform: ["PS4"],
    img: "https://play-lh.googleusercontent.com/t5oeiArOj1ud5N_FcP_rb4EDW1Jfb9hdduZymL3HPeqihlnEEChx0-vrBctx-NyS1Oo=w526-h296-rw",
  },
];
